<template>
  <main class="container">
    <header class="main-header">
      <h1>AI Development History</h1>
      <h2>A Timeline of Artificial Intelligence Milestones</h2>
    </header>
    <Timeline />
  </main>
  <footer class="footer">
    Generated by Gemini Pro. A Journey Through AI.
  </footer>
</template>

<script setup>
import Timeline from './components/Timeline.vue';
</script>

<style scoped>
.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 2rem;
}

.main-header {
  text-align: center;
  margin-bottom: 4rem;
}

.main-header h1 {
  font-size: 3.5rem;
  margin-bottom: 0.5rem;
}

.main-header h2 {
  font-family: var(--font-body);
  font-size: 1.2rem;
  font-weight: 300;
  color: var(--text-secondary);
  text-shadow: none;
}

.footer {
  text-align: center;
  margin-top: 5rem;
  padding: 2rem;
  font-family: var(--font-body);
  font-size: 0.8rem;
  color: var(--text-secondary);
  opacity: 0.5;
}

@media (max-width: 768px) {
  .main-header h1 {
    font-size: 2.5rem;
  }
  .main-header h2 {
    font-size: 1rem;
  }
}
</style>